//! The Clean Up panel's folder recognition, shared with the JSON CLI.
//! These are name/structure heuristics, not authorization to delete anything.
use crate::{Tree, NO_PARENT};
use std::path::{Component, Path};

pub const MIN_BYTES: u64 = 50_000_000;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Kind {
    NodeModules,
    PythonEnvironment,
    RustBuild,
    NextBuild,
    XcodeDerivedData,
    DeviceSupport,
    AppCaches,
    ToolCaches,
    BunCache,
}

impl Kind {
    pub fn id(self) -> &'static str {
        match self {
            Self::NodeModules => "node_modules",
            Self::PythonEnvironment => "python_environment",
            Self::RustBuild => "rust_build",
            Self::NextBuild => "next_build",
            Self::XcodeDerivedData => "xcode_derived_data",
            Self::DeviceSupport => "device_support",
            Self::AppCaches => "app_caches",
            Self::ToolCaches => "tool_caches",
            Self::BunCache => "bun_cache",
        }
    }

    /// Existing panel labels; kept here so both interfaces describe the same rule.
    pub fn description(self) -> &'static str {
        match self {
            Self::NodeModules => "npm packages, reinstallable",
            Self::PythonEnvironment => "Python environment, reinstallable",
            Self::RustBuild => "Rust build output",
            Self::NextBuild => "Next.js build output",
            Self::XcodeDerivedData => "Xcode build data",
            Self::DeviceSupport => "Device symbols, re-downloaded when needed",
            Self::AppCaches => "App caches, rebuilt automatically",
            Self::ToolCaches => "Caches, rebuilt or re-downloaded when needed",
            Self::BunCache => "Bun package cache, re-downloaded when needed",
        }
    }

    /// A cautious description of what the matching folder usually contains.
    /// This is context for a review, not a claim that deleting the folder is
    /// safe or that its allocated bytes will be recovered.
    pub fn impact(self) -> Impact {
        match self {
            Self::NodeModules => Impact {
                class: "usually_rebuildable",
                note: "Usually reproducible from the project's package manifest; review local changes first.",
            },
            Self::PythonEnvironment => Impact {
                class: "usually_rebuildable",
                note: "Usually reproducible from the project's Python metadata; review local packages first.",
            },
            Self::RustBuild => Impact {
                class: "usually_rebuildable",
                note: "Build output is usually regenerated by Cargo; confirm no build artifacts are being inspected.",
            },
            Self::NextBuild => Impact {
                class: "usually_rebuildable",
                note: "Build output is usually regenerated by Next.js; confirm no deployment artifact is needed.",
            },
            Self::XcodeDerivedData => Impact {
                class: "usually_rebuildable",
                note: "Xcode can regenerate this build data; verify no active build or debugging session depends on it.",
            },
            Self::DeviceSupport => Impact {
                class: "usually_re_downloadable",
                note: "Device symbols can usually be downloaded again when needed; check active device workflows.",
            },
            Self::AppCaches => Impact {
                class: "usually_rebuildable",
                note: "Application cache data is often rebuilt, but the owning app may be using it or store state beside it.",
            },
            Self::ToolCaches => Impact {
                class: "usually_rebuildable",
                note: "Tool cache data is often rebuilt or downloaded again; check active jobs and local edits first.",
            },
            Self::BunCache => Impact {
                class: "usually_re_downloadable",
                note: "Bun can usually download these packages again; check active installs before removal.",
            },
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Impact {
    pub class: &'static str,
    pub note: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Candidate {
    pub node: u32,
    pub kind: Kind,
}

/// Why a candidate matched the shared rule. The names are borrowed from the
/// scanned tree so the JSON report can show concrete evidence without adding
/// another classifier in the CLI.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Evidence<'a> {
    pub matched_name: &'a str,
    pub parent_name: Option<&'a str>,
    pub marker_name: Option<&'a str>,
}

impl Candidate {
    pub fn evidence<'a>(self, t: &'a Tree) -> Evidence<'a> {
        let node = self.node as usize;
        let parent = t.parents[node];
        let parent_name = (parent != NO_PARENT).then(|| t.name(parent as usize));
        let marker_name = match self.kind {
            Kind::PythonEnvironment if t.name(node) == "venv" => Some("pyvenv.cfg"),
            Kind::RustBuild => Some("Cargo.toml"),
            Kind::NextBuild => Some("package.json"),
            _ => None,
        };
        Evidence {
            matched_name: t.name(node),
            parent_name,
            marker_name,
        }
    }
}

fn contains(t: &Tree, directory: u32, name: &str) -> bool {
    directory != NO_PARENT
        && t.kids(directory as usize)
            .iter()
            .any(|&i| t.name(i as usize) == name)
}

fn kind(t: &Tree, i: u32) -> Option<Kind> {
    let parent = t.parents[i as usize];
    let parent_name = if parent != NO_PARENT { t.name(parent as usize) } else { "" };
    // Marker lookups happen only for the named artifact, not every sibling.
    match t.name(i as usize) {
        "node_modules" => Some(Kind::NodeModules),
        ".venv" => Some(Kind::PythonEnvironment),
        "venv" if contains(t, i, "pyvenv.cfg") => Some(Kind::PythonEnvironment),
        "target" if contains(t, parent, "Cargo.toml") => Some(Kind::RustBuild),
        ".next" if contains(t, parent, "package.json") => Some(Kind::NextBuild),
        "DerivedData" if parent_name == "Xcode" => Some(Kind::XcodeDerivedData),
        "iOS DeviceSupport" | "macOS DeviceSupport" | "watchOS DeviceSupport" => {
            Some(Kind::DeviceSupport)
        }
        "Caches" if parent_name == "Library" || parent_name == "CoreSimulator" => {
            Some(Kind::AppCaches)
        }
        ".cache" | ".npm" | ".gradle" => Some(Kind::ToolCaches),
        "cache"
            if parent_name == "install"
                && t.parents[parent as usize] != NO_PARENT
                && t.name(t.parents[parent as usize] as usize) == ".bun" =>
        {
            Some(Kind::BunCache)
        }
        _ => None,
    }
}

fn is_system_cache_container(t: &Tree, i: u32) -> bool {
    // /Library and /System are system-owned. The GUI often scans the Data
    // volume through /System/Volumes/Data, so its user cache paths remain
    // eligible only below /System/Volumes/Data/Users.
    let path = t.path(i as usize);
    let mut components = Path::new(&path).components();
    if components.next() != Some(Component::RootDir) {
        return false;
    }
    let named = |component: Option<Component<'_>>, wanted: &str| {
        matches!(component, Some(Component::Normal(name)) if name == wanted)
    };
    let first = components.next();
    if named(first, "Library") {
        return true;
    }
    if !named(first, "System") {
        return false;
    }
    !(named(components.next(), "Volumes")
        && named(components.next(), "Data")
        && named(components.next(), "Users"))
}

fn is_apple_managed_cache(t: &Tree, i: u32) -> bool {
    let name = t.name(i as usize);
    name == "com.apple" || name.starts_with("com.apple.")
}

fn granular_container(kind: Kind, name: &str) -> bool {
    matches!(kind, Kind::AppCaches) || (kind == Kind::ToolCaches && name == ".cache")
}

fn root_granular_kind(t: &Tree) -> Option<Kind> {
    if t.is_empty() {
        return None;
    }
    let path = t.path(0);
    let names: Vec<_> = path
        .components()
        .filter_map(|component| match component {
            Component::Normal(name) => name.to_str(),
            _ => None,
        })
        .collect();
    match names.last().copied() {
        Some(".cache") => Some(Kind::ToolCaches),
        Some("Caches") if names.get(names.len().saturating_sub(2)) == Some(&"Library") => {
            Some(Kind::AppCaches)
        }
        Some("Caches")
            if names.get(names.len().saturating_sub(2)) == Some(&"CoreSimulator") =>
        {
            Some(Kind::AppCaches)
        }
        _ => None,
    }
}

fn add_granular_children(
    t: &Tree,
    container: u32,
    container_kind: Kind,
    min_bytes: u64,
    found: &mut Vec<Candidate>,
) {
    if container_kind == Kind::AppCaches && is_system_cache_container(t, container) {
        return;
    }
    for &child in t.kids(container as usize) {
        let i = child as usize;
        if t.alloc[i] < min_bytes
            || !t.is_dir(i)
            || t.name(i) == ".Trash"
            || is_apple_managed_cache(t, child)
        {
            continue;
        }
        found.push(Candidate {
            node: child,
            kind: container_kind,
        });
    }
}

/// Existing panel semantics: visit descendants (not the scan root), skip
/// `.Trash`, and never descend into a recognized folder, even below threshold.
/// Size ties use paths so parallel scan scheduling cannot reorder the report.
pub fn find(t: &Tree, min_bytes: u64) -> Vec<Candidate> {
    let mut found = Vec::new();
    if t.is_empty() {
        return found;
    }
    let mut stack = Vec::new();
    if let Some(root_kind) = root_granular_kind(t) {
        add_granular_children(t, 0, root_kind, min_bytes, &mut found);
    } else {
        stack.push(0);
    }
    while let Some(i) = stack.pop() {
        for &child in t.kids(i) {
            let c = child as usize;
            // Skip this subtree, not later siblings (the final sort decides order).
            if t.alloc[c] < min_bytes || !t.is_dir(c) || t.name(c) == ".Trash" {
                continue;
            }
            if let Some(kind) = kind(t, child) {
                if granular_container(kind, t.name(c)) {
                    // Cache containers are boundaries. Listing their direct
                    // children gives useful, reviewable targets without
                    // overlapping the container or walking into nested rules.
                    add_granular_children(t, child, kind, min_bytes, &mut found);
                } else {
                    found.push(Candidate { node: child, kind });
                }
            } else {
                stack.push(c);
            }
        }
    }
    found.sort_by(|a, b| {
        t.alloc[b.node as usize]
            .cmp(&t.alloc[a.node as usize])
            .then_with(|| t.compare_paths(a.node as usize, b.node as usize))
    });
    found
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Sizes are set per node as given (not aggregated). Siblings must be
    /// added consecutively, as a scan appends them; `link` then lists them.
    fn add(scan: &mut Tree, parent: u32, name: &str, is_dir: bool, bytes: u64) -> u32 {
        if parent == NO_PARENT {
            *scan = Tree::with_root(name);
            scan.alloc[0] = bytes;
            scan.logical[0] = bytes;
            return 0;
        }
        assert!(
            scan.parents.last() == Some(&parent) || !scan.parents.contains(&parent),
            "siblings are contiguous"
        );
        scan.push(name, parent, bytes, bytes, is_dir)
    }

    fn link(mut scan: Tree) -> Tree {
        scan.link_children();
        scan
    }

    #[test]
    fn recognizes_all_existing_panel_rules_and_no_new_ones() {
        // Each row has an independent context, including the legacy name-only
        // marker behavior. No filesystem access is needed for classification.
        let cases = [
            (
                "node_modules",
                "project",
                "",
                "",
                "",
                Some(Kind::NodeModules),
            ),
            (
                ".venv",
                "project",
                "",
                "",
                "",
                Some(Kind::PythonEnvironment),
            ),
            (
                "venv",
                "project",
                "",
                "",
                "pyvenv.cfg",
                Some(Kind::PythonEnvironment),
            ),
            ("venv", "project", "", "", "", None),
            (
                "target",
                "project",
                "",
                "Cargo.toml",
                "",
                Some(Kind::RustBuild),
            ),
            ("target", "project", "", "", "", None),
            (
                ".next",
                "project",
                "",
                "package.json",
                "",
                Some(Kind::NextBuild),
            ),
            (".next", "project", "", "", "", None),
            (
                "DerivedData",
                "Xcode",
                "",
                "",
                "",
                Some(Kind::XcodeDerivedData),
            ),
            ("DerivedData", "other", "", "", "", None),
            (
                "iOS DeviceSupport",
                "any",
                "",
                "",
                "",
                Some(Kind::DeviceSupport),
            ),
            (
                "macOS DeviceSupport",
                "any",
                "",
                "",
                "",
                Some(Kind::DeviceSupport),
            ),
            (
                "watchOS DeviceSupport",
                "any",
                "",
                "",
                "",
                Some(Kind::DeviceSupport),
            ),
            ("Caches", "Library", "", "", "", Some(Kind::AppCaches)),
            ("Caches", "CoreSimulator", "", "", "", Some(Kind::AppCaches)),
            ("Caches", "other", "", "", "", None),
            (".cache", "any", "", "", "", Some(Kind::ToolCaches)),
            (".npm", "any", "", "", "", Some(Kind::ToolCaches)),
            (".gradle", "any", "", "", "", Some(Kind::ToolCaches)),
            ("cache", "install", ".bun", "", "", Some(Kind::BunCache)),
            ("cache", "install", "other", "", "", None),
            ("cache", "other", ".bun", "", "", None),
            (".build", "project", "", "Package.swift", "", None),
            ("Downloads", "home", "", "", "", None),
        ];
        for (name, parent, grandparent, sibling, child, expected) in cases {
            let mut scan = Tree::default();
            add(&mut scan, NO_PARENT, "/root", true, 0);
            let gp = add(&mut scan, 0, grandparent, true, MIN_BYTES);
            let p = add(&mut scan, gp, parent, true, MIN_BYTES);
            let i = add(&mut scan, p, name, true, MIN_BYTES);
            if !sibling.is_empty() {
                add(&mut scan, p, sibling, false, 0);
            }
            if !child.is_empty() {
                add(&mut scan, i, child, false, 0);
            }
            let scan = link(scan);
            assert_eq!(kind(&scan, i), expected, "{grandparent}/{parent}/{name}");
            let expected_candidates = match expected {
                Some(Kind::AppCaches) => Vec::new(),
                Some(Kind::ToolCaches) if name == ".cache" => Vec::new(),
                Some(kind) => vec![Candidate { node: i, kind }],
                None => Vec::new(),
            };
            assert_eq!(
                find(&scan, MIN_BYTES),
                expected_candidates
            );
        }
    }

    #[test]
    fn cache_containers_expose_individual_non_apple_children() {
        let mut scan = Tree::with_root("/Users/test");
        let library = scan.push("Library", 0, MIN_BYTES * 5, MIN_BYTES * 5, true);
        let dot_cache = scan.push(".cache", 0, MIN_BYTES * 2, MIN_BYTES * 2, true);
        let caches = scan.push("Caches", library, MIN_BYTES * 4, MIN_BYTES * 4, true);
        let app = scan.push("com.example.editor", caches, MIN_BYTES * 2, MIN_BYTES * 2, true);
        let apple = scan.push("com.apple.system", caches, MIN_BYTES, MIN_BYTES, true);
        let trash = scan.push(".Trash", caches, MIN_BYTES, MIN_BYTES, true);
        scan.push("node_modules", app, MIN_BYTES, MIN_BYTES, true);
        scan.push("visible", apple, MIN_BYTES, MIN_BYTES, true);
        scan.push("keep", trash, MIN_BYTES, MIN_BYTES, true);
        let pip = scan.push("pip", dot_cache, MIN_BYTES, MIN_BYTES, true);
        let nested = scan.push("node_modules", pip, MIN_BYTES, MIN_BYTES, true);
        scan.push("package", nested, MIN_BYTES, MIN_BYTES, true);
        let scan = link(scan);

        let candidates = find(&scan, MIN_BYTES);
        assert_eq!(
            candidates
                .iter()
                .map(|c| scan.path(c.node as usize).display().to_string())
                .collect::<Vec<_>>(),
            vec![
                "/Users/test/Library/Caches/com.example.editor".to_string(),
                "/Users/test/.cache/pip".to_string(),
            ]
        );
        assert!(candidates.iter().all(|c| c.node != caches && c.node != dot_cache));
        assert!(!candidates.iter().any(|c| c.node == nested));

        let evidence = candidates[0].evidence(&scan);
        assert_eq!(evidence.matched_name, "com.example.editor");
        assert_eq!(evidence.parent_name, Some("Caches"));
        assert_eq!(evidence.marker_name, None);
    }

    #[test]
    fn system_cache_containers_are_not_quick_wins() {
        let mut scan = Tree::default();
        add(&mut scan, NO_PARENT, "/", true, 0);
        let library = add(&mut scan, 0, "Library", true, MIN_BYTES * 2);
        let caches = add(&mut scan, library, "Caches", true, MIN_BYTES * 2);
        add(&mut scan, caches, "third.party", true, MIN_BYTES * 2);
        let scan = link(scan);
        assert!(find(&scan, MIN_BYTES).is_empty());

        let mut scan = Tree::default();
        add(&mut scan, NO_PARENT, "/System", true, 0);
        let library = add(&mut scan, 0, "Library", true, MIN_BYTES * 2);
        let caches = add(&mut scan, library, "Caches", true, MIN_BYTES * 2);
        add(&mut scan, caches, "third.party", true, MIN_BYTES * 2);
        let scan = link(scan);
        assert!(find(&scan, MIN_BYTES).is_empty());

        let mut scan = Tree::with_root("/System/Volumes/Data");
        let users = scan.push("Users", 0, MIN_BYTES * 2, MIN_BYTES * 2, true);
        let user = scan.push("test", users, MIN_BYTES * 2, MIN_BYTES * 2, true);
        let library = scan.push("Library", user, MIN_BYTES * 2, MIN_BYTES * 2, true);
        let caches = scan.push("Caches", library, MIN_BYTES * 2, MIN_BYTES * 2, true);
        add(&mut scan, caches, "third.party", true, MIN_BYTES * 2);
        let scan = link(scan);
        assert_eq!(find(&scan, MIN_BYTES).len(), 1);
    }

    #[test]
    fn explicit_cache_root_lists_children_but_not_the_root() {
        for root in [
            "/Users/test/Library/Caches",
            "/Users/test/.cache",
            "/Users/test/Library/Developer/CoreSimulator/Caches",
            "/System/Volumes/Data/Users/test/Library/Caches",
        ] {
            let mut scan = Tree::with_root(root);
            let child = scan.push("cache-entry", 0, MIN_BYTES, MIN_BYTES, true);
            let scan = link(scan);
            let candidates = find(&scan, MIN_BYTES);
            assert_eq!(candidates.len(), 1, "{root}");
            assert_eq!(candidates[0].node, child, "{root}");
            assert_ne!(candidates[0].node, 0, "{root}");
        }
        for root in [
            "/System/Volumes/Data/Library/Caches",
            "/System/Volumes/Data/Library/Developer/CoreSimulator/Caches",
        ] {
            let mut system = Tree::with_root(root);
            system.push("system-entry", 0, MIN_BYTES, MIN_BYTES, true);
            assert!(find(&link(system), MIN_BYTES).is_empty(), "{root}");
        }
    }

    #[test]
    fn preserves_panel_traversal_threshold_and_partial_candidates() {
        let mut scan = Tree::default();
        add(
            &mut scan,
            NO_PARENT,
            "/root/node_modules",
            true,
            MIN_BYTES * 10,
        );
        let trash = add(&mut scan, 0, ".Trash", true, MIN_BYTES * 2);
        add(&mut scan, 0, ".cache", false, MIN_BYTES * 2);
        let matched = add(&mut scan, 0, "node_modules", true, MIN_BYTES);
        let small = add(&mut scan, 0, ".gradle", true, MIN_BYTES - 1);
        add(&mut scan, trash, "node_modules", true, MIN_BYTES * 2);
        add(&mut scan, matched, ".venv", true, MIN_BYTES);
        // Deliberately inconsistent size catches descent under a small match.
        add(&mut scan, small, ".venv", true, MIN_BYTES);
        let mut scan = link(scan);
        scan.complete[matched as usize] = false;
        assert_eq!(
            find(&scan, MIN_BYTES),
            vec![Candidate {
                node: matched,
                kind: Kind::NodeModules
            }]
        );
    }

    #[test]
    fn size_ties_are_lexical_independent_of_discovery_order() {
        for names in [["z", "a"], ["a", "z"]] {
            let mut scan = Tree::default();
            add(&mut scan, NO_PARENT, "/root", true, 0);
            let first = add(&mut scan, 0, names[0], true, MIN_BYTES);
            let second = add(&mut scan, 0, names[1], true, MIN_BYTES);
            let large = add(&mut scan, 0, ".npm", true, MIN_BYTES * 2);
            let first_cache = add(&mut scan, first, ".cache", true, MIN_BYTES);
            let second_cache = add(&mut scan, second, ".cache", true, MIN_BYTES);
            let first_item = add(&mut scan, first_cache, "pip", true, MIN_BYTES);
            let second_item = add(&mut scan, second_cache, "pip", true, MIN_BYTES);
            let scan = link(scan);
            let expected = if names[0] == "a" {
                vec![large, first_item, second_item]
            } else {
                vec![large, second_item, first_item]
            };
            assert_eq!(
                find(&scan, MIN_BYTES)
                    .iter()
                    .map(|c| c.node)
                    .collect::<Vec<_>>(),
                expected
            );
        }
    }
}
